### ISSUE TITLE
Error Message in Block with cost-history

### ISSUE THREAD

**Issue by uzdry** [aqibsaeed/Urban-Sound-Classification#3]
Hi, i am getting following error message:

---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-13-b62e644ad9a7> in <module>()
      4     sess.run(init)
      5     for epoch in range(training_epochs):
----> 6         _, cost = sess.run([optimizer, cost_function], feed_dict={X: train_x, Y: train_y})
      7         cost_history = np.append(cost_history, cost)
      8 

/usr/lib/python3.6/site-packages/tensorflow/python/client/session.py in run(self, fetches, feed_dict, options, run_metadata)
    787     try:
    788       result = self._run(None, fetches, feed_dict, options_ptr,
--> 789                          run_metadata_ptr)
    790       if run_metadata:
    791         proto_data = tf_session.TF_GetBuffer(run_metadata_ptr)

/usr/lib/python3.6/site-packages/tensorflow/python/client/session.py in _run(self, handle, fetches, feed_dict, options, run_metadata)
    973                 'Cannot feed value of shape %r for Tensor %r, '
    974                 'which has shape %r'
--> 975                 % (np_val.shape, subfeed_t.name, str(subfeed_t.get_shape())))
    976           if not self.graph.is_feedable(subfeed_t):
    977             raise ValueError('Tensor %s may not be fed.' % subfeed_t)

ValueError: Cannot feed value of shape (0, 0) for Tensor 'Placeholder_1:0', which has shape '(?, 10)'

**Comment by aqibsaeed** [comment]
Make sure the Y placeholder that you defined have valid shape.

**Comment by uzdry** [comment]
Could you elaborate? I have used the urbansound8k package just like you. Would that not mean that it should be valid?

**Comment by aqibsaeed** [comment]
ValueError: Cannot feed value of shape (0, 0) for Tensor 'Placeholder_1:0', which has shape '(?, 10)'

This error suggests you are trying to feed data of shape (0,0) in a Tensorflow placeholder with shape of (?,10) 10 columns. This has nothing to do with urbansound8k. Please make sure the variables you have defined have valid shape. In particular, check train_y.

**Comment by uzdry** [comment]
I do not get it. I used the exact notebook you provided. Am i supposed to change something there?

**Comment by aqibsaeed** [comment]
You do not need to change anything, but errors occur during reproducibility. Just make sure the data you are trying to feed have the same shape. Otherwise, it is really hard for me to comment on what is going wrong by just looking at  "ValueError: Cannot feed value of shape (0, 0) for Tensor 'Placeholder_1:0', which has shape '(?, 10)'" this error.

**Comment by gvance** [comment]
I was able to reproduce this error by using different sources and labels but failed to provide the correct value for `num_labels` which agrees with your advice:
> Please make sure the variables you have defined have valid shape. In particular, check **train_y.**

**Comment by kubark42** [comment]
> I do not get it. I used the exact notebook you provided. Am i supposed to change something there?

@uzdry you might look at https://github.com/aqibsaeed/Urban-Sound-Classification/issues/6. The sound file paths are hardcoded, and they're tricky to see because they're in the middle of the file so if you just run the entire notebook it will fail with that error. The solution is to update the `parent_dir` line to point to the sound files on your computer.
